### POST one user

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Yerko 2 con mas de 20 caracteres",
  "username": "Yerko_2",
  "password": "Contraseña123"
}

### Get all users
GET http://localhost:3000/users

### Get user by ID
GET http://localhost:3000/users/67e7327672a2675c732722b3

### 